//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Collections.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Collections.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This binary tree is full..
        /// </summary>
        internal static string BinaryTreeIsFull {
            get {
                return ResourceManager.GetString("BinaryTreeIsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer is empty..
        /// </summary>
        internal static string BufferIsEmpty {
            get {
                return ResourceManager.GetString("BufferIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capacity must be greater than or equal to zero..
        /// </summary>
        internal static string CapacityMustBeGreaterOrEqualZero {
            get {
                return ResourceManager.GetString("CapacityMustBeGreaterOrEqualZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column and row count must be larger than 0..
        /// </summary>
        internal static string ColumnAndRowCountBiggerThan0 {
            get {
                return ResourceManager.GetString("ColumnAndRowCountBiggerThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object to compare against is null..
        /// </summary>
        internal static string ComparingNullObject {
            get {
                return ResourceManager.GetString("ComparingNullObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deque is empty..
        /// </summary>
        internal static string DequeIsEmpty {
            get {
                return ResourceManager.GetString("DequeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edge between the vertices specified allready exists..
        /// </summary>
        internal static string EdgeAllreadyExists {
            get {
                return ResourceManager.GetString("EdgeAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The edge specified was not found on this vertex..
        /// </summary>
        internal static string EdgeNotFoundOnVertex {
            get {
                return ResourceManager.GetString("EdgeNotFoundOnVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graph is empty..
        /// </summary>
        internal static string GraphIsEmpty {
            get {
                return ResourceManager.GetString("GraphIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The heap is empty..
        /// </summary>
        internal static string HeapIsEmpty {
            get {
                return ResourceManager.GetString("HeapIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible matrices.  For this operation the matrices should be of the same size..
        /// </summary>
        internal static string IncompatibleMatricesSameSize {
            get {
                return ResourceManager.GetString("IncompatibleMatricesSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible matrices for this operation.  The rows of the input matrix must be equal to the columns of this matrix..
        /// </summary>
        internal static string IncompatibleMatricesTimes {
            get {
                return ResourceManager.GetString("IncompatibleMatricesTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial values can not be null..
        /// </summary>
        internal static string InitialValuesNull {
            get {
                return ResourceManager.GetString("InitialValuesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation can not be done on the type of matrix specified..
        /// </summary>
        internal static string InvalidOperationWrongMatrixType {
            get {
                return ResourceManager.GetString("InvalidOperationWrongMatrixType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The probability must be between 0.1 and 0.9.
        /// </summary>
        internal static string InvalidProbability {
            get {
                return ResourceManager.GetString("InvalidProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is allready contained in the tree..
        /// </summary>
        internal static string ItemAllreadyInTree {
            get {
                return ResourceManager.GetString("ItemAllreadyInTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is allready in the list..
        /// </summary>
        internal static string ItemAlreadyInList {
            get {
                return ResourceManager.GetString("ItemAlreadyInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item is not in the universe of the set..
        /// </summary>
        internal static string ItemNotInUniverse {
            get {
                return ResourceManager.GetString("ItemNotInUniverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key specified is allready in the collection..
        /// </summary>
        internal static string KeyAllreadyExists {
            get {
                return ResourceManager.GetString("KeyAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key does not exist in the list..
        /// </summary>
        internal static string KeyDoesNotExist {
            get {
                return ResourceManager.GetString("KeyDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lower bound must be larger or equal to zero..
        /// </summary>
        internal static string LowerBoundLargerThanZero {
            get {
                return ResourceManager.GetString("LowerBoundLargerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix is null..
        /// </summary>
        internal static string MatrixIsNull {
            get {
                return ResourceManager.GetString("MatrixIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum level must be bigger than 0..
        /// </summary>
        internal static string MaximumLevelBiggerThan0 {
            get {
                return ResourceManager.GetString("MaximumLevelBiggerThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of edge must be the same as the type of graph (Undirected / Directed).
        /// </summary>
        internal static string MismatchedEdgeType {
            get {
                return ResourceManager.GetString("MismatchedEdgeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough space in the target array..
        /// </summary>
        internal static string NotEnoughSpaceInTargetArray {
            get {
                return ResourceManager.GetString("NotEnoughSpaceInTargetArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of values can not be greater than the number of columns..
        /// </summary>
        internal static string NumberOfValuesDoNotAgreeWithNumberOfColumns {
            get {
                return ResourceManager.GetString("NumberOfValuesDoNotAgreeWithNumberOfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of values can not be greater than the number of rows..
        /// </summary>
        internal static string NumberOfValuesDoNotAgreeWithNumberOfRows {
            get {
                return ResourceManager.GetString("NumberOfValuesDoNotAgreeWithNumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbers provided must be greater than zero..
        /// </summary>
        internal static string NumbersGreaterThanZero {
            get {
                return ResourceManager.GetString("NumbersGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only add 1 or more items..
        /// </summary>
        internal static string OnlyAddPositiveAmount {
            get {
                return ResourceManager.GetString("OnlyAddPositiveAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property have some other type than .
        /// </summary>
        internal static string PropertyHaveOtherType {
            get {
                return ResourceManager.GetString("PropertyHaveOtherType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows and columns must be nonnegative values..
        /// </summary>
        internal static string RowsOrColumnsInvalid {
            get {
                return ResourceManager.GetString("RowsOrColumnsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search tree is empty..
        /// </summary>
        internal static string SearchTreeIsEmpty {
            get {
                return ResourceManager.GetString("SearchTreeIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index of an item in a set can not be negative..
        /// </summary>
        internal static string SetIndexMustBePostive {
            get {
                return ResourceManager.GetString("SetIndexMustBePostive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is only valid on a directed graph. For undirected graphs, rather test for weak connectedness..
        /// </summary>
        internal static string UndirectedGraphStrongConnectedness {
            get {
                return ResourceManager.GetString("UndirectedGraphStrongConnectedness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation requested can only be done if the sets share the same universe..
        /// </summary>
        internal static string UniverseNotTheSame {
            get {
                return ResourceManager.GetString("UniverseNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upper bound must be larger than the lower bound specified..
        /// </summary>
        internal static string UpperBoundMustBeLargerThanLowerBound {
            get {
                return ResourceManager.GetString("UpperBoundMustBeLargerThanLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertex already exists in the graph..
        /// </summary>
        internal static string VertexAlreadyExists {
            get {
                return ResourceManager.GetString("VertexAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertex specified could not be found in the graph..
        /// </summary>
        internal static string VertexCouldNotBeFound {
            get {
                return ResourceManager.GetString("VertexCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vertex specified does not form part of this edge..
        /// </summary>
        internal static string VertexNotPartOfEdge {
            get {
                return ResourceManager.GetString("VertexNotPartOfEdge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x must be larger than or equal to y..
        /// </summary>
        internal static string XMustBeLargerThanY {
            get {
                return ResourceManager.GetString("XMustBeLargerThanY", resourceCulture);
            }
        }
    }
}
